language: python
python:
 - '3.5'

before_script:
 - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="projet.application.settings.travis"

services:
 - postgresql

script:
 - python3 /home/pilt/applications/nutella/projet/manage.py test
