language: python
python:
 - '3.5'

before_script:
 - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="application.settings.travis"

services:
 - postgresql

script:
 - python projet/manage.py test
