# Generated by Django 2.2.5 on 2020-01-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='aliment',
            field=models.ManyToManyField(blank=True, null=True, to='aliment.Aliment'),
        ),
    ]
