# Generated by Django 2.2.5 on 2019-09-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aliment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aliment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_aliment", models.CharField(max_length=50, verbose_name="nom")),
                ("note_nutritionelle", models.CharField(max_length=10)),
                ("categorie", models.IntegerField()),
                ("description", models.CharField(max_length=500)),
                ("lieux", models.CharField(max_length=150)),
                ("url", models.CharField(max_length=150)),
            ],
        ),
    ]
