# Generated by Django 2.2.5 on 2019-10-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aliment", "0002_aliment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="aliment", name="categorie",),
        migrations.AddField(
            model_name="aliment",
            name="categorie",
            field=models.ManyToManyField(to="aliment.Categorie"),
        ),
    ]
