# Generated by Django 2.2.5 on 2019-10-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aliment", "0003_auto_20191017_1636"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aliment", old_name="nom_aliment", new_name="nom",
        ),
        migrations.AddField(
            model_name="categorie",
            name="nom",
            field=models.CharField(default="oui", max_length=50, verbose_name="nom"),
            preserve_default=False,
        ),
    ]
