# Generated by Django 2.2.5 on 2019-10-30 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("aliment", "0004_auto_20191017_1640"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aliment", old_name="url", new_name="url_img",
        ),
        migrations.AddField(
            model_name="aliment",
            name="url_off",
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categorie",
            name="nom",
            field=models.CharField(max_length=80, verbose_name="nom"),
        ),
        migrations.DeleteModel(name="Choice",),
        migrations.DeleteModel(name="Question",),
    ]
