# Generated by Django 2.2.5 on 2019-11-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aliment", "0005_auto_20191030_1308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorie",
            name="nom",
            field=models.CharField(max_length=80, unique=True, verbose_name="nom"),
        ),
    ]
