# Generated by Django 2.2.5 on 2019-11-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliment', '0006_auto_20191115_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aliment',
            name='lieux',
        ),
        migrations.AddField(
            model_name='aliment',
            name='repere_nutritionel',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
    ]
