# Generated by Django 2.2.5 on 2019-11-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliment', '0007_auto_20191121_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliment',
            name='repere_nutritionel',
        ),
        migrations.AddField(
            model_name='aliment',
            name='acide_100g',
            field=models.DecimalField(decimal_places=4, default=0.123, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aliment',
            name='glucide_100g',
            field=models.DecimalField(decimal_places=4, default=0.123, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aliment',
            name='salt_100g',
            field=models.DecimalField(decimal_places=4, default=0.123, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aliment',
            name='sugar_100g',
            field=models.DecimalField(decimal_places=4, default=0.123, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aliment',
            name='note_nutritionelle',
            field=models.CharField(max_length=1),
        ),
    ]
