# Generated by Django 2.2.5 on 2020-01-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliment', '0008_auto_20191128_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='acide_100g',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='glucide_100g',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='salt_100g',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='aliment',
            name='sugar_100g',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
