# Generated by Django 2.2.5 on 2020-04-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliment', '0009_auto_20200108_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='insert',
            field=models.BooleanField(default=False),
        ),
    ]
